#!/bin/bash
DIR_RAMDISK="ramdisk"
FILE_RAMDISK="ramdisk.img"

# Generate ramdisk file
cd $DIR_RAMDISK && find . | cpio -o -H newc | gzip > ../$FILE_RAMDISK && cd ..

# Make kernel-updated.elf
python mkelf.py -o gbkernel.elf 0@0x00200000 1@0x01200000,ramdisk

# Clear temporary files
rm $FILE_RAMDISK